# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PostgresMcpServer < Formula
  desc "Model Control Protocol (MCP) server for PostgreSQL databases"
  homepage "https://github.com/mgorunuch/postgres-mcp-server"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mgorunuch/postgres-mcp-server/releases/download/v0.1.9/postgres-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "e77169316b4e9d0b249871f477019b20aeb978411b6e4acbdabd6c664db72982"

      def install
        bin.install "postgres-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mgorunuch/postgres-mcp-server/releases/download/v0.1.9/postgres-mcp-server_Darwin_arm64.tar.gz"
      sha256 "b029e4d2167dcb1d4a3ca7eaa075036edac366942b54bb68b19f43e38462799b"

      def install
        bin.install "postgres-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mgorunuch/postgres-mcp-server/releases/download/v0.1.9/postgres-mcp-server_Linux_x86_64.tar.gz"
      sha256 "1bed1512e60c4c4014d8a34eed9eb17b27afe35b8d9328fad9d29c64cf5f15cb"
      def install
        bin.install "postgres-mcp-server"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mgorunuch/postgres-mcp-server/releases/download/v0.1.9/postgres-mcp-server_Linux_arm64.tar.gz"
      sha256 "1ad02e7f265b4cd656955e452180e0b0c6bfb0f20d49f1826ce2d0d1385001b6"
      def install
        bin.install "postgres-mcp-server"
      end
    end
  end

  test do
    system "#{bin}/postgres-mcp-server --version"
  end
end
