# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PostgresqlMcpServer < Formula
  desc "Model Control Protocol (MCP) server for PostgreSQL databases"
  homepage "https://github.com/mgorunuch/postgres-mcp-server"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mgorunuch/postgres-mcp-server/releases/download/v0.1.8/postgresql-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "de5e2b6d5899fa94d24f0175a756b2d7f246c9ef6594ac36cb04996746710563"

      def install
        bin.install "postgresql-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mgorunuch/postgres-mcp-server/releases/download/v0.1.8/postgresql-mcp-server_Darwin_arm64.tar.gz"
      sha256 "9eb422c9508ca11c9738eb4f7295f437d557467f25157be3226f61e90c92e804"

      def install
        bin.install "postgresql-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mgorunuch/postgres-mcp-server/releases/download/v0.1.8/postgresql-mcp-server_Linux_x86_64.tar.gz"
      sha256 "771eb68916cadc26f4e2a59611ad65e1cbb8fad5eeaeeaf5e1637876586f737a"
      def install
        bin.install "postgresql-mcp-server"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mgorunuch/postgres-mcp-server/releases/download/v0.1.8/postgresql-mcp-server_Linux_arm64.tar.gz"
      sha256 "1119ce72a39bc68a0692a94ca0a16fd9c38b2104564b5ee8eaa16f6cab2dd1e5"
      def install
        bin.install "postgresql-mcp-server"
      end
    end
  end

  test do
    system "#{bin}/postgresql-mcp-server --version"
  end
end
