# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PostgresMcpServer < Formula
  desc "Model Control Protocol (MCP) server for PostgreSQL databases"
  homepage "https://github.com/mgorunuch/postgres-mcp-server"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mgorunuch/postgres-mcp-server/releases/download/v0.1.11/postgres-mcp-server_Darwin_x86_64.tar.gz"
      sha256 "b3c135ab762a59260515c2ac4684736d2a5712ee13de3152fe98f31afae45c6a"

      def install
        bin.install "postgres-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mgorunuch/postgres-mcp-server/releases/download/v0.1.11/postgres-mcp-server_Darwin_arm64.tar.gz"
      sha256 "ac80c96b0ac13a90f22ef80d1be2ab0c3e2f3c1237e02da981c96cbf010d9f93"

      def install
        bin.install "postgres-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mgorunuch/postgres-mcp-server/releases/download/v0.1.11/postgres-mcp-server_Linux_x86_64.tar.gz"
      sha256 "7a21aa8081cdfe6f94aa59ef42e4a6052d8a2d0ea23ff99382bef5b141e16b05"
      def install
        bin.install "postgres-mcp-server"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mgorunuch/postgres-mcp-server/releases/download/v0.1.11/postgres-mcp-server_Linux_arm64.tar.gz"
      sha256 "ca0ea3a0a016121b0bad3d7e1f82945f95e86ddfc4e809f8cc05b9c60f294fd1"
      def install
        bin.install "postgres-mcp-server"
      end
    end
  end

  test do
    system "#{bin}/postgres-mcp-server --version"
  end
end
